import {generate,CRUISE} from './theater.js';
const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
let world,scale=1,ox=0,oy=0,w=0,h=0,selection=null,base,charted=new Set([0]);
const point=p=>[ox+p.x*scale,oy+p.y*scale];
function fit(){const b=world.bounds;scale=Math.min((w-70)/(b.maxX-b.minX),(h-90)/(b.maxY-b.minY));ox=w/2-(b.minX+b.maxX)/2*scale;oy=h/2-(b.minY+b.maxY)/2*scale;draw();}
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);fit();}
function zoom(f,x=w/2,y=h/2){const next=Math.max(.002,Math.min(.5,scale*f));f=next/scale;ox=x-(x-ox)*f;oy=y-(y-oy)*f;scale=next;draw();}
function load(seed){world=generate(seed);base=world.home;selection=null;charted=new Set([0]);$('#map-name').textContent=`Theater ${seed} · ${world.regions.length} archipelagos`;$('#regions').textContent=`${world.regions.length} regions`;$('#landforms').textContent=`${world.islands.length} landforms`;const p=world.metrics.passages;$('#distances').textContent=`${world.holdings.length} holdings. Regional center-to-center passages: ${Math.round(Math.min(...p))}–${Math.round(Math.max(...p))} seconds at cruise. Actual base-to-base flights vary; tap one to measure.`;document.querySelectorAll('[data-seed]').forEach(b=>b.classList.toggle('active',+b.dataset.seed===seed));select(null);resize();window.atlasWorld=world;}
function draw(){if(!world)return;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#071c29');g.addColorStop(1,'#113b48');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const full=$('#layer').value==='full';
ctx.strokeStyle='#507b842c';ctx.lineWidth=1;ctx.setLineDash([3,9]);for(const[a,b]of world.links){const A=point(world.regions[a]),B=point(world.regions[b]);ctx.beginPath();ctx.moveTo(...A);ctx.lineTo(...B);ctx.stroke();}ctx.setLineDash([]);
const labelBoxes=[];for(const r of world.regions){const [x,y]=point(r),known=full||charted.has(r.id);if(!known){ctx.beginPath();ctx.ellipse(x,y,r.radius*scale*1.6,r.radius*scale, r.heading,0,Math.PI*2);ctx.fillStyle='#58787918';ctx.fill();ctx.strokeStyle='#79979866';ctx.setLineDash([4,7]);ctx.stroke();ctx.setLineDash([]);}ctx.font='600 11px system-ui';const labelWidth=Math.min(220,ctx.measureText(r.name.toUpperCase()).width+24);let labelY=y-r.radius*scale-17;for(let tries=0;tries<12&&labelBoxes.some(b=>Math.abs(b.x-x)<(b.width+labelWidth)/2&&Math.abs(b.y-labelY)<30);tries++)labelY-=30;labelY=Math.max(105,labelY);labelBoxes.push({x,y:labelY,width:labelWidth});ctx.fillStyle=selection?.region===r.id?'#edbe84':'#93b5b4';ctx.font='600 11px system-ui';ctx.textAlign='center';ctx.fillText(r.name.toUpperCase(),Math.max(labelWidth/2,Math.min(w-labelWidth/2,x)),labelY);ctx.font='10px system-ui';ctx.fillStyle='#71979c';if(w>600)ctx.fillText(known?r.identity:'Approximate chart · survey needed',x,labelY+14);}
for(const t of world.islands){if(!full&&!charted.has(t.region))continue;ctx.beginPath();t.coast.forEach(([x,y],i)=>{const p=point({x:t.x+x,y:t.y+y});i?ctx.lineTo(...p):ctx.moveTo(...p);});ctx.closePath();ctx.strokeStyle='#3eaaa543';ctx.lineWidth=Math.max(3,150*scale);ctx.stroke();ctx.fillStyle=t.kind==='reef'?'#517d68':t.kind==='mainland'?'#346958':'#4b7b64';ctx.fill();ctx.strokeStyle='#b3b892';ctx.lineWidth=.65;ctx.stroke();if(t.kind==='mainland'){const[x,y]=point(t);ctx.beginPath();ctx.ellipse(x,y,t.rx*.35*scale,t.ry*.75*scale,t.a,0,Math.PI*2);ctx.fillStyle='#214f48';ctx.fill();}}
for(const b of world.holdings){if(!full&&!charted.has(b.region))continue;const[x,y]=point(b);ctx.fillStyle=b.id===base.id?'#95f3ce':'#f0d5a9';if(b.role.includes('airfield'))ctx.fillRect(x-3,y-5,6,10);else if(b.role==='radar'){ctx.beginPath();ctx.moveTo(x,y-5);ctx.lineTo(x+5,y+4);ctx.lineTo(x-5,y+4);ctx.closePath();ctx.fill();}else {ctx.beginPath();ctx.moveTo(x,y-4);ctx.lineTo(x+4,y);ctx.lineTo(x,y+4);ctx.lineTo(x-4,y);ctx.closePath();ctx.fill();}}
const [bx,by]=point(base);ctx.strokeStyle='#97f0d299';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(bx,by,CRUISE*15*scale,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#9cdac7';ctx.font='10px system-ui';ctx.textAlign='left';ctx.fillText('15 seconds from launch',bx+5,by+CRUISE*15*scale+12);
if(selection){const[x,y]=point(selection);ctx.strokeStyle='#ecc28e';ctx.lineWidth=2;ctx.strokeRect(x-8,y-8,16,16);ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(x,y);ctx.stroke();ctx.setLineDash([]);}
// A scale bar grounded in the game speed makes empty water assessable.
let units=10000;while(units*scale>w*.25)units/=2;const length=units*scale;ctx.strokeStyle='#adc5c5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w-length-20,h-24);ctx.lineTo(w-20,h-24);ctx.stroke();ctx.fillStyle='#adc5c5';ctx.font='10px system-ui';ctx.textAlign='right';ctx.fillText(`${Math.round(units/CRUISE)}s at cruise`,w-20,h-33);
}
function select(s){selection=s;$('#selected-name').textContent=s?s.name:'Choose a destination';$('#selected-detail').textContent=s?`${world.regions[s.region].identity}. ${Math.round(Math.hypot(s.x-base.x,s.y-base.y)/CRUISE)} seconds one-way from ${world.regions[base.region].name}; ${Math.round(Math.hypot(s.x-world.home.x,s.y-world.home.y)/CRUISE)} seconds from home.`:'Tap a region or installation. The mint circle shows 15 seconds of flight from your launch base.';$('#reveal').disabled=!s||charted.has(s.region);$('#base').disabled=!s?.role?.includes('airfield');draw();}
const contacts=new Map();let drag=null,moved=0,pinch=0;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);contacts.set(e.pointerId,[e.offsetX,e.offsetY]);drag=[e.offsetX,e.offsetY];moved=0;if(contacts.size===2){const p=[...contacts.values()];pinch=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);}});
canvas.addEventListener('pointermove',e=>{if(!contacts.has(e.pointerId))return;contacts.set(e.pointerId,[e.offsetX,e.offsetY]);if(contacts.size===2){const p=[...contacts.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(pinch)zoom(d/pinch,(p[0][0]+p[1][0])/2,(p[0][1]+p[1][1])/2);pinch=d;moved=100;return;}if(drag){ox+=e.offsetX-drag[0];oy+=e.offsetY-drag[1];moved+=Math.hypot(e.offsetX-drag[0],e.offsetY-drag[1]);drag=[e.offsetX,e.offsetY];draw();}});
canvas.addEventListener('pointerup',e=>{contacts.delete(e.pointerId);if(moved<8){const full=$('#layer').value==='full';const candidates=world.holdings.filter(t=>full||charted.has(t.region));const near=candidates.map(t=>({t,d:Math.hypot(point(t)[0]-e.offsetX,point(t)[1]-e.offsetY)})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<20)select(near.t);else{const p={x:(e.offsetX-ox)/scale,y:(e.offsetY-oy)/scale};const r=world.regions.reduce((a,b)=>Math.hypot(b.x-p.x,b.y-p.y)<Math.hypot(a.x-p.x,a.y-p.y)?b:a);select({...r,region:r.id,role:null});}}drag=null;pinch=0;});
canvas.addEventListener('pointercancel',e=>{contacts.delete(e.pointerId);drag=null;pinch=0;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001),e.offsetX,e.offsetY);},{passive:false});
$('#plus').onclick=()=>zoom(1.5);$('#minus').onclick=()=>zoom(1/1.5);$('#fit').onclick=fit;$('#layer').onchange=()=>{select(null);draw();};$('#reveal').onclick=()=>{charted.add(selection.region);select(selection);};$('#base').onclick=()=>{base=selection;select(selection);};document.querySelectorAll('[data-seed]').forEach(b=>b.onclick=()=>load(+b.dataset.seed));$('#another').onclick=()=>load((world.seed*1664525+1013904223)>>>0);window.addEventListener('resize',resize);load(1942);
