// Runs through the real simulation in-browser with deterministic setups.
export async function campaignChecks(api) {
  const { game, startGame, update, keys, CONFIG, requestCarrier, launchTorpedo } = api;
  const { defenders, updateCampaign } = await import('../src/campaign.js');
  const { damageShip, hitsShip } = await import('../src/ships.js');
  const { launchBomb, updateBombs } = await import('../src/bombs.js');
  const { updateStrikes } = await import('../src/strikes.js');
  const { selectSortie, availableBases } = await import('../src/bases.js');
  const { AIRCRAFT, aircraftUnlocked } = await import('../src/aircraft-types.js');
  const { recordSession, sessionSummary } = await import('../src/session-report.js');
  const { updateCarrierFlight } = await import('../src/carrier.js');
  const { onLand } = await import('../src/surface.js');
  const checks = [];
  const check = (name, ok) => checks.push({ name, ok: !!ok });
  const reset = () => { for (const key of Object.keys(keys)) keys[key] = false; api.setSeed(1942); startGame(); };
  const fly = () => { game.player.flight = 'flying'; game.player.altitude = CONFIG.render.flightHeight; game.player.speed = CONFIG.player.speedCruise; };
  const naval = () => {
    fly(); game.rank = 2; game.combatSorties = CONFIG.progression.aircraftSorties.corsair; game.rescue = { ...(game.rescue || {}), status: 'complete' };
    const c = game.ships[0]; c.active = true; c.hp = c.maxHp; c.a = -Math.PI / 2;
    // Isolate landing tolerances from route motion; task groups are tested separately.
    game.ships.forEach(s => { delete s.fleet; });
    const base = game.bases.find(b => b.kind === 'carrier'); if (base) base.available = true;
    game.player.aircraft = 'corsair'; game.player.loadout = 'torpedoes';
    game.player.x = c.x + 1000; game.player.y = c.y + 1000;
  };
  const step = seconds => { for (let i = 0; i < Math.round(seconds / .02); i++) update(.02); };
  reset();
  check('campaign starts at a friendly airfield in a bomb-equipped P38', game.territories.length >= 6 && game.territories[0].owner === 'us' && game.player.flight === 'landed' && game.player.aircraft === 'p38' && game.player.loadout === 'bombs');
  const layout = () => JSON.stringify(game.territories.map(t => [t.x,t.y,t.radius,t.owner]));
  const initialLayout = layout(); reset();
  check('same campaign seed reproduces the island chain', layout() === initialLayout);
  api.setSeed(927); startGame();
  check('different campaign seeds create different island chains', layout() !== initialLayout); reset(); fly();
  reset();
  const home = game.bases.find(b => b.kind === 'airfield' && b.owner === 'us');
  check('rank zero cannot select a Corsair', !selectSortie(game, { baseId: home.id, aircraft: 'corsair', loadout: 'bombs' }));
  check('P38 cannot equip torpedoes', !selectSortie(game, { baseId: home.id, aircraft: 'p38', loadout: 'torpedoes' }));
  check('new aircraft stay locked before their milestones', ['dauntless','avenger','p51'].every(id => !aircraftUnlocked(game,id)));
  game.flightSeconds = 10000;
  check('idle flight time cannot unlock aircraft', !aircraftUnlocked(game,'dauntless'));
  game.flightSeconds = 0;
  game.score = CONFIG.progression.aircraftUnlocks.dauntless;
  check('score alone cannot bypass combat sortie qualifications', !aircraftUnlocked(game,'dauntless'));
  game.combatSorties = CONFIG.progression.aircraftSorties.dauntless - 1;
  check('Dauntless stays locked one combat sortie before qualification', !aircraftUnlocked(game,'dauntless'));
  game.combatSorties++;
  check('first combat return unlocks Dauntless without waiting', game.flightSeconds === 0 && aircraftUnlocked(game,'dauntless'));

  check('score and completed combat sorties unlock the Dauntless at an airfield', selectSortie(game,{baseId:home.id,aircraft:'dauntless',loadout:'bombs'}));
  fly(); launchBomb(game);
  check('Dauntless releases a heavier, faster-falling bomb', game.bombs[0].damage === 40 && game.bombs[0].maxLife < CONFIG.bomb.fallSeconds);
  reset(); game.score = CONFIG.progression.aircraftUnlocks.p51; game.combatSorties = CONFIG.progression.aircraftSorties.p51;
  check('points alone do not unlock advanced naval campaign aircraft', !aircraftUnlocked(game,'avenger') && !aircraftUnlocked(game,'p51'));
  game.rank = 2;
  check('completed rescue, points and combat sorties unlock all five aircraft', Object.keys(AIRCRAFT).length === 5 && Object.keys(AIRCRAFT).every(id => aircraftUnlocked(game,id)));
  check('Avenger rejects bombs and equips torpedoes', !selectSortie(game,{baseId:home.id,aircraft:'avenger',loadout:'bombs'}) && selectSortie(game,{baseId:home.id,aircraft:'avenger',loadout:'torpedoes'}));
  fly(); launchTorpedo();
  check('Avenger launches a heavy anti-ship torpedo', game.torpedoes[0]?.damage === 40);
  game.player.flight = 'landed';
  check('Mustang is selectable at an airfield with the fastest cruise speed', selectSortie(game,{baseId:home.id,aircraft:'p51',loadout:'bombs'}) && CONFIG.aircraft.p51.speedCruise > CONFIG.aircraft.p38.speedCruise);
  reset(); fly();
  check('sortie changes are rejected in flight', !selectSortie(game, { baseId: home.id, aircraft: 'p38', loadout: 'bombs' }));
  const field = game.airfields.find(f => f.owner === 'enemy');
  for (const f of game.airfields) f.launchTimer = 1000;
  for (const s of game.ships) s.launchTimer = 1000;
  field.launchTimer = 0; updateStrikes(game, .02);
  check('living enemy airfield launches a strike group', game.enemies.filter(e => e.sourceId === field.id).length === CONFIG.strike.groupSize + CONFIG.strike.escortCount);
  game.enemies = [];
  game.player.x = field.x - CONFIG.bomb.driftSpeed * CONFIG.bomb.fallSeconds;
  game.player.y = field.y; game.player.a = 0;
  check('bomb release consumes one of two bombs', launchBomb(game) && game.player.bombAmmo === 1);
  check('bomb cooldown blocks duplicate release', !launchBomb(game));
  updateBombs(game, CONFIG.bomb.fallSeconds + .01);
  const damaged = field.hp;
  check('falling bomb damages airfield through its actual impact', damaged < field.maxHp);
  updateBombs(game, CONFIG.bomb.cooldown);
  check('second bomb can be released after cooldown', launchBomb(game) && game.player.bombAmmo === 0);
  updateBombs(game, CONFIG.bomb.fallSeconds + .01);
  check('two-bomb sortie can disable an airfield', field.hp === 0);
  field.launchTimer = 0; updateStrikes(game, .02);
  check('destroyed airfield stops launching new attackers', !game.enemies.some(e => e.sourceId === field.id));
  check('empty bomb loadout cannot fire', !launchBomb(game));
  const enemyCarrier = game.ships.find(s => s.team === 'jp' && s.kind === 'carrier');
  enemyCarrier.x = home.x + 2500; enemyCarrier.y = home.y;
  enemyCarrier.launchTimer = 0; game.strikeLaunchCooldown = 0; updateStrikes(game, .02);
  const attackers = game.enemies.filter(e => e.sourceId === enemyCarrier.id);
  check('enemy carrier launches attackers from its actual flight deck', attackers.length === CONFIG.strike.groupSize + CONFIG.strike.escortCount && attackers.every(e => Math.hypot(e.x - enemyCarrier.x, e.y - enemyCarrier.y) < CONFIG.strike.formationSpacing * attackers.length));
  const homeField = game.airfields.find(f => f.id === home.airfieldId), homeHp = homeField.hp;
  check('organized raids include bombers and escorts', attackers.filter(e => e.strikeRole === 'bomber').length === CONFIG.strike.groupSize && attackers.filter(e => e.strikeRole === 'escort').length === CONFIG.strike.escortCount);
  const attacker = attackers.find(e => e.strikeRole === 'bomber'); attacker.x = homeField.x; attacker.y = homeField.y;
  updateStrikes(game, .02);
  check('unintercepted strike damages its target base and retreats', homeField.hp === homeHp - CONFIG.strike.baseDamage && attacker.phase === 'retreat');
  const escort = attackers.find(e => e.strikeRole === 'escort');
  escort.x = homeField.x; escort.y = homeField.y; const escortHp = homeField.hp;
  updateStrikes(game, .02);
  check('escort reaching a base cannot apply bombing damage', homeField.hp === escortHp && escort.phase === 'retreat');
  enemyCarrier.hp = 0; enemyCarrier.launchTimer = 0; game.enemies = [];
  updateStrikes(game, .02);
  check('sinking enemy carrier stops subsequent strikes', !game.enemies.some(e => e.sourceId === enemyCarrier.id));

  reset(); fly();
  for (const f of game.airfields) f.launchTimer = f.owner === 'enemy' ? 0 : 1000;
  for (const s of game.ships) s.launchTimer = 1000;
  updateStrikes(game, .01);
  const firstSources = new Set(game.enemies.filter(e => e.strike).map(e => e.sourceId));
  check('simultaneously overdue facilities launch only one formation', firstSources.size === 1 && game.enemies.length === CONFIG.strike.groupSize + CONFIG.strike.escortCount);
  updateStrikes(game, CONFIG.strike.launchGap - .1);
  check('global raid spacing prevents a second immediate launch', new Set(game.enemies.filter(e => e.strike).map(e => e.sourceId)).size === 1);
  updateStrikes(game, .11);
  check('active offensive cap prevents overlapping major raids after cooldown', new Set(game.enemies.filter(e => e.strike).map(e => e.sourceId)).size === 1);
  game.enemies = []; updateStrikes(game,.02);
  check('next local offensive launches after the previous formation clears', game.enemies.filter(e => e.strike).length === CONFIG.strike.groupSize + CONFIG.strike.escortCount);
  reset();
  const targetShip = game.ships.find(s => s.team === 'jp');
  Object.assign(targetShip, {x:20000,y:20000,a:.73,hp:100,maxHp:100});
  const impact = (along,lateral) => {
    game.particles = [];
    const x = targetShip.x + Math.cos(targetShip.a)*along - Math.sin(targetShip.a)*lateral;
    const y = targetShip.y + Math.sin(targetShip.a)*along + Math.cos(targetShip.a)*lateral;
    game.bombs.push({x,y,vx:0,vy:0,life:.01}); updateBombs(game,.02);
  };
  impact(0,targetShip.width);
  check('near-miss bomb splashes in water without ship damage', targetShip.hp === 100 && game.particles.some(p => p.kind === 'splash') && !game.particles.some(p => p.kind === 'fire'));
  impact(targetShip.length*.48,targetShip.width*.3);
  check('bomb outside tapered bow splashes despite bounding-box overlap', targetShip.hp === 100 && game.particles.some(p => p.kind === 'splash'));
  impact(0,0);
  check('precise bomb impact damages a rotated hull', targetShip.hp === 100-CONFIG.bomb.damage && game.particles.some(p => p.kind === 'fire') && !game.particles.some(p => p.kind === 'splash'));
  check('shoreline classifies island center as land and open ocean as water', onLand(game.territories[0],game.territories) && !onLand({x:20000,y:20000},game.territories));
  reset();
  game.player.x = 20000; game.player.y = 20000;
  game.score = CONFIG.progression.rescueScore;
  updateCampaign(game, .02, () => {});
  check('distant rank unlock waits for player arrival before rescue attack', game.rescue.status === 'active' && !game.rescue.launched && !game.enemies.some(e => e.rescue));
  game.player.x = game.ships[0].x; game.player.y = game.ships[0].y;

  updateCampaign(game, .02, () => {});
  check('earning rank activates a vulnerable carrier rescue', game.rank === 1 && game.rescue.status === 'active' && game.ships[0].active && game.enemies.some(e => e.rescue));
  check('carrier remains unavailable before its rescue', !availableBases(game).some(b => b.kind === 'carrier'));
  game.ships[0].hp = 0; updateCampaign(game, .02, () => {});
  check('carrier loss schedules a retry without ending campaign', game.rescue.status === 'retry' && game.mode === 'play');
  updateCampaign(game, CONFIG.progression.rescueRetry + .1, () => {});
  check('failed carrier rescue can be attempted again', game.rescue.status === 'active' && game.ships[0].hp === game.ships[0].maxHp && game.enemies.some(e => e.rescue));
  game.enemies = game.enemies.filter(e => !e.rescue);
  game.player.x = game.ships[0].x; game.player.y = game.ships[0].y;
  updateCampaign(game, .02, () => {});
  check('letting rescue attackers escape cannot unlock the carrier', game.rank === 1 && game.rescue.status === 'retry');
  updateCampaign(game, CONFIG.progression.rescueRetry + .1, () => {});
  for (const enemy of game.enemies.filter(e => e.rescue).slice(0, 2)) { enemy.hp = 1; game.bullets.push({ x: enemy.x, y: enemy.y, vx: 0, vy: 0, life: 1 }); }
  update(0);
  check('shooting down rescue attackers records required intercepts', game.rescue.intercepts === 2);
  game.enemies = game.enemies.filter(e => !e.rescue);
  game.player.x = game.ships[0].x; game.player.y = game.ships[0].y;
  updateCampaign(game, .02, () => {});
  check('clearing rescue attackers near carrier unlocks naval operations', game.rank === 2 && game.rescue.status === 'complete' && availableBases(game).some(b => b.kind === 'carrier'));
  game.combatSorties = CONFIG.progression.aircraftSorties.corsair;
  const carrierBase = game.bases.find(b => b.kind === 'carrier');
  check('land-based P38 cannot transfer onto a carrier', !selectSortie(game, { baseId: carrierBase.id, aircraft: 'p38', loadout: 'bombs' }));
  check('safely landed pilot can transfer and equip a naval sortie', selectSortie(game, { baseId: carrierBase.id, aircraft: 'corsair', loadout: 'torpedoes' }) && game.player.baseId === carrierBase.id && game.player.x === game.ships[0].x);
  reset(); fly();
  check('no waves or enemies spawn at the carrier', !('waveNum' in game) && game.enemies.length === 0);
  const t = game.territories.find(t => t.owner === 'enemy' && !game.airfields.some(f => f.territory === t.id));
  game.player.x = t.x; game.player.y = t.y;
  update(.02);
  check('entering hostile airspace activates its fighter patrol once', t.activated && game.enemies.length === t.fighters);
  const count = game.enemies.length;
  update(.02);
  check('active territories do not repeatedly respawn defenders', game.enemies.length === count);
  check('defenders prevent capture', t.progress === 0 && defenders(game, t) > 0);
  const ship = game.ships.find(s => s.team === 'jp' && s.kind === 'destroyer');
  check('fast rounds intersect the oriented hull', hitsShip({ prevX: ship.x - Math.cos(ship.a) * 200,
    prevY: ship.y - Math.sin(ship.a) * 200, x: ship.x + Math.cos(ship.a) * 200, y: ship.y + Math.sin(ship.a) * 200 }, ship));
  const hullHp = ship.hp;
  game.bullets.push({ x: ship.x, y: ship.y, vx: 0, vy: 0, life: 1 });
  update(.02);
  check('bullets cannot damage ship hulls', ship.hp === hullHp);
  for (let i = 0; i < 40; i++) { game.bullets.push({ x: ship.x, y: ship.y, vx: 0, vy: 0, life: .1 }); update(.02); }
  check('sustained gunfire cannot sink a ship', ship.hp === hullHp);
  const before = game.score;
  damageShip(ship, ship.hp);
  damageShip(ship, 5);
  check('destroyers sink and award points only once', ship.hp === 0 && game.score === before + CONFIG.ship.score);
  game.enemies.forEach(e => { if (e.territory === t.id) e.hp = 0; });
  // Hold a small real flight orbit inside the capture zone.
  game.player.x = t.x; game.player.y = t.y; game.player.a = 0;
  keys.KeyD = true;
  step(CONFIG.conquest.captureSeconds / 2);
  check('clear territory gains capture progress while flying inside it', t.progress > 1 && t.owner === 'enemy');
  game.player.x = t.x + CONFIG.conquest.captureRadius + 200;
  update(.02);
  check('leaving the zone resets an unfinished capture', t.progress === 0);
  game.player.x = t.x; game.player.y = t.y;
  step(CONFIG.conquest.captureSeconds + .2);
  check('holding cleared airspace captures territory', t.owner === 'us');
  const capturedScore = game.score;
  step(1);
  check('captured territory stays captured without awarding points repeatedly', t.owner === 'us' && game.score === capturedScore);
  reset(); naval();
  game.player.hp = 35; step(.5);
  check('flying no longer repairs health automatically', game.player.hp === 35);
  game.player.x = 4000; requestCarrier();
  check('takeoff action has no effect in flight', game.player.flight === 'flying' && game.player.x === 4000);
  check('campaign has no selected target', !('target' in game));
  const c = game.ships[0];
  const approach = (x, y, a) => {
    game.player.x = x; game.player.y = y; game.player.a = a;
    game.player.speed = CONFIG.player.speedCruise; game.player.deckApproach = false;
  };
  approach(c.x + CONFIG.carrier.lateralTolerance + 10, c.y + c.length / 2 + 10, c.a);
  step(.2);
  check('off-center pass does not land', game.player.flight === 'flying');
  approach(c.x, c.y - c.length / 2 - 10, c.a + Math.PI);
  step(1.2);
  check('reverse-direction deck pass does not land', game.player.flight === 'flying');
  approach(c.x, c.y + c.length / 2 + 10, c.a + .8);
  step(.2);
  check('crossing the stern at a bad angle does not land', game.player.flight === 'flying');
  approach(c.x, c.y, c.a);
  step(.1);
  check('being over the deck without a stern approach does not land', game.player.flight === 'flying');
  approach(c.x, c.y + c.length / 2 + 70, c.a);
  step(.1);
  check('aligned final approach keeps manual flight control', game.player.flight === 'flying' && game.player.altitude < CONFIG.render.flightHeight);
  keys.KeyD = true; step(.15); keys.KeyD = false;
  check('pilot can steer away from the approach', game.player.flight === 'flying' && game.player.a > c.a + .2);
  approach(c.x + 16, c.y + c.length / 2 + 10, c.a + .3);
  step(.08);
  check('small offset and heading errors are accepted', game.player.flight === 'landing');
  game.player.flight = 'flying';
  approach(c.x + 30, c.y + c.length / 2 + 10, c.a);
  step(.08);
  check('stern crossing leaves time for a deck correction', game.player.flight === 'flying' && game.player.deckApproach);
  game.player.x = c.x + 22;
  update(.02);
  check('correcting alignment after the stern still catches a wire', game.player.flight === 'landing');
  game.player.flight = 'flying';
  approach(c.x + 6, c.y + c.length / 2 + 40, c.a);
  game.player.bombAmmo = 0; game.player.torpedoAmmo = 0;
  for (let i = 0; i < 300 && game.player.flight !== 'landed'; i++) update(.02);
  check('aligned stern crossing lands without requesting assistance', game.player.flight === 'landed'
    && Math.abs(game.player.x - c.x - 6) < 1 && game.player.altitude === CONFIG.carrier.deckHeight);
  check('landing immediately refills both ordnance types', game.player.bombAmmo === 2 && game.player.torpedoAmmo === 2);
  const parkedHp = game.player.hp;
  game.enemies.push({ x: game.player.x, y: game.player.y, a: 0, hp: 3, speed: 0, turn: 0, fireCd: 99, wobble: 0, raider: true });
  update(.001);
  check('parked player and overlapping enemy do not ram each other', game.player.hp >= parkedHp && game.enemies.some(e => e.raider && e.hp === 3 && e.speed === 0));
  game.enemies = game.enemies.filter(e => !(e.raider && e.speed === 0));
  keys.Space = true; step(.1);
  check('guns stay safe on deck', game.bullets.every(b => b.fromAlly || b.fromShip));
  step(1);
  check('deck repairs restore health over time', game.player.hp > 35 && game.player.hp < CONFIG.player.hp);
  step(10);
  check('repairs cap at full health and cool guns', game.player.hp === CONFIG.player.hp && game.player.heat === 0);
  keys.Space = false; requestCarrier();
  check('takeoff begins from the deck', game.player.flight === 'takeoff');
  step(CONFIG.carrier.takeoffSeconds + .1);
  check('takeoff restores normal flight at cruising altitude', game.player.flight === 'flying'
    && game.player.altitude === CONFIG.render.flightHeight && game.player.y < c.y - c.length / 2);
  reset(); naval();
  check('sortie starts with exactly two torpedoes', game.player.torpedoAmmo === 2);
  check('torpedo launches and consumes one round', launchTorpedo() && game.torpedoes.length === 1 && game.player.torpedoAmmo === 1);
  check('torpedo cooldown prevents duplicate launches', !launchTorpedo() && game.player.torpedoAmmo === 1);
  const torp = game.torpedoes[0], patrol = game.ships.find(s => s.team === 'jp' && s.kind === 'destroyer');
  torp.x = patrol.x - 50; torp.y = patrol.y; torp.vx = CONFIG.torpedo.speed; torp.vy = 0; torp.distance = 100;
  step(.3);
  check('armed torpedo sinks a destroyer through real collisions', patrol.hp === 0 && game.torpedoes.length === 0);
  step(CONFIG.torpedo.cooldown);
  check('second torpedo consumes the last round', launchTorpedo() && game.player.torpedoAmmo === 0);
  step(CONFIG.torpedo.range / CONFIG.torpedo.speed + .1);
  check('empty loadout stays empty in flight and spent torpedoes expire', !launchTorpedo() && game.player.torpedoAmmo === 0 && game.torpedoes.length === 0);
  game.player.x = game.ships[0].x; game.player.y = game.ships[0].y + CONFIG.carrier.length / 2 + 30; game.player.a = game.ships[0].a;
  game.player.bombAmmo = 0; game.player.torpedoAmmo = 0;
  for (let i = 0; i < 300 && game.player.flight !== 'landed'; i++) update(.02);
  check('torpedoes cannot launch on deck', !launchTorpedo());
  step(CONFIG.torpedo.rearmSeconds + .1);
  check('carrier rearms both torpedoes', game.player.torpedoAmmo === 2);
  reset();
  for (let i = 0; i < game.territories.length; i++) {
    const island = game.territories[i]; if (island.owner === 'us' || !island.stronghold) continue;
    fly(); game.airfields.filter(f => f.territory === island.id).forEach(f => { f.hp = 0; });
    game.player.x = island.x; game.player.y = island.y; game.player.a = 0;
    update(.02);
    game.enemies.forEach(e => { e.hp = 0; });
    game.ships.filter(s => s.territory === island.id).forEach(s => damageShip(s, s.hp));
    keys.KeyD = true;
    step(CONFIG.conquest.captureSeconds + .2);
  }
  game.ships.filter(s => s.team === 'jp' && s.kind === 'carrier').forEach(s => damageShip(s, s.hp)); update(.02);
  check('stronghold and principal carrier victory does not require every island or escort', game.mode === 'victory' && game.territories.some(t => t.owner === 'enemy') && game.ships.some(s => s.team === 'jp' && s.hp > 0));
  reset();
  check('new campaign resets territory ownership, fleet and flight state', game.mode === 'play'
    && game.territories[0].owner === 'us' && game.territories.slice(1).every(t => t.owner === 'enemy' && !t.activated) && game.player.flight === 'landed'
    && game.ships.every(s => s.hp === s.maxHp));
  update(.02);
  check('a wingman musters at the start of a campaign', game.allies.filter(f => f.role === 'wing').length === api.CONFIG.airWar.wing.slots[0] && game.allies.every(f => f.team === 'us'));
  fly(); game.player.x = 20000; game.player.y = 20000;
  const friendStart = game.allies.map(f => ({ x: f.x, y: f.y, d: Math.hypot(f.x - 20000, f.y - 20000) }));
  game.raidTimer = 0; update(.02);
  const raider = game.enemies.find(e => e.raider);
  check('roaming Zero can spawn far from all territories', !!raider && raider.territory === undefined);
  const raidDistance = Math.hypot(raider.x - game.player.x, raider.y - game.player.y);
  check('roaming Zero arrives outside the viewport', raidDistance > Math.hypot(api.view.W, api.view.H) / 2);
  game.raidTimer = 0; update(.02);
  check('roaming interceptors do not stack', game.enemies.filter(e => e.raider).length === 1);
  const pursuitTarget = { x: game.player.x, y: game.player.y };
  for (let i = 0; i < 100; i++) { update(.02); Object.assign(game.player, pursuitTarget); }
  check('roaming Zero pursues outside island defense boundaries', Math.hypot(raider.x - game.player.x, raider.y - game.player.y) < raidDistance);
  check('wingmen fly to rejoin a distant player', game.allies.every((f, i) => Math.hypot(f.x - game.player.x, f.y - game.player.y) < friendStart[i].d - 100));
  const friendly = game.allies[0]; friendly.x = 0; friendly.y = 0; friendly.a = 0; friendly.fireCd = 0;
  raider.x = 200; raider.y = 0;
  // Wingmen shoot at the lead point, so allow a few ticks to bring the guns onto it.
  for (let i = 0; i < 10; i++) update(.02);
  check('wingmen fire at nearby enemy fighters', game.bullets.some(b => b.fromAlly));
  const hp = friendly.hp;
  game.ebullets.push({ x: friendly.x, y: friendly.y, vx: 0, vy: 0, life: 1 }); update(.02);
  check('friendly fighters can be damaged by hostile fire', friendly.hp < hp);
  reset();
  // Exercise the actual takeoff/landing transitions, without credit for empty circuits or allied score.
  const completeLanding = () => {
    Object.assign(game.player, { flight: 'landing', flightTime: 0,
      arrival: { x: home.x, y: home.y, a: home.a, speed: 100 } });
    updateCarrierFlight(game, CONFIG.carrier.landingSeconds + .01);
  };
  requestCarrier(); completeLanding();
  check('empty takeoff and landing cannot farm combat sorties', game.combatSorties === 0);
  requestCarrier(); game.score += 100; completeLanding();
  check('allied score during a sortie cannot qualify the player', game.combatSorties === 0);
  requestCarrier(); game.playerMerit += 1; completeLanding();
  check('landing after personal combat merit credits exactly one sortie', game.combatSorties === 1);
  updateCarrierFlight(game, 20);
  check('waiting parked cannot repeatedly credit the same sortie', game.combatSorties === 1);

  reset();
  check('generated campaign includes airfield, port and radar roles', ['airfield','port','radar'].every(role => game.territories.some(t => t.role === role)));
  const port = game.territories.find(t => t.role === 'port');
  const fleet = game.ships[0];
  Object.assign(port, { owner: 'us', established: 0 });
  Object.assign(fleet, { active: true, x: port.x, y: port.y, hp: 80 });
  updateCampaign(game, 1, () => {});
  check('newly captured port needs establishment before repairing the fleet', fleet.hp === 80);
  port.established = CONFIG.conquest.establishSeconds;
  updateCampaign(game, 1, () => {});
  check('established friendly port repairs a nearby living fleet', fleet.hp > 80);
  fleet.hp = 0; updateCampaign(game, 1, () => {});
  check('port cannot resurrect a sunken carrier', fleet.hp === 0);
  port.integrity = 0; updateCampaign(game, .01, () => {});
  check('destroyed outpost is recaptured and campaign can continue', port.owner === 'enemy' && !port.activated && game.mode === 'play');

  reset();
  const radar = game.territories.find(t => t.role === 'radar'); radar.owner = 'us'; radar.established = CONFIG.conquest.establishSeconds;
  for (const f of game.airfields) f.launchTimer = 1000;
  for (const s of game.ships) s.launchTimer = 1000;
  game.player.x = 20000; game.player.y = 20000;
  const radarRaid = { x: radar.x, y: radar.y, a: 0, hp: 3, speed: 0, turn: 0, fireCd: 99, strike: true, strikeRole: 'bomber', targetBaseId: home.id, phase: 'attack' };
  game.enemies = [radarRaid]; updateStrikes(game, .01);
  check('friendly radar detects a raid beyond the player vicinity', radarRaid.detected);
  radar.owner = 'enemy'; updateStrikes(game, .01);
  check('losing radar removes distant raid detection', !radarRaid.detected);

  reset();
  const forward = game.airfields.find(f => f.owner === 'enemy');
  const forwardIsland = game.territories.find(t => t.id === forward.territory);
  const forwardBase = game.bases.find(b => b.airfieldId === forward.id);
  forward.owner = 'us'; forwardIsland.owner = 'us'; forwardBase.owner = 'us'; forwardBase.available = true;
  selectSortie(game, { baseId: forwardBase.id, aircraft: 'p38', loadout: 'bombs' });
  forward.hp = 0; updateCampaign(game, .01, () => {});
  check('lost forward airfield evacuates a grounded player to a surviving base', forward.owner === 'enemy' && !forwardBase.available && game.player.baseId === home.id && game.mode === 'play');
  game.airfields.find(f => f.id === home.airfieldId).hp = 0; updateCampaign(game, .01, () => {});
  check('loss of every operational base ends the campaign', game.mode === 'over' && availableBases(game).length === 0);
  reset(); fly();
  const freshField = game.airfields.find(f => f.owner === 'enemy');
  const freshIsland = game.territories.find(t => t.id === freshField.territory);
  freshField.hp = 0; freshIsland.activated = true;
  game.ships.filter(s => s.territory === freshIsland.id).forEach(s => { s.hp = 0; });
  game.player.x = freshIsland.x; game.player.y = freshIsland.y;
  updateCampaign(game, CONFIG.conquest.captureSeconds, () => {});
  freshField.hp -= CONFIG.strike.baseDamage; updateCampaign(game, .01, () => {});
  check('freshly captured airfield survives one bomber impact', freshIsland.owner === 'us' && freshField.owner === 'us' && freshField.hp > 0);
  reset(); recordSession(game);
  const reportIsland = game.territories[1];
  reportIsland.owner = 'us'; game.time = 123; game.unlockedAircraft.push('dauntless'); recordSession(game);
  reportIsland.owner = 'enemy'; game.ships[0].hp = 0; game.raidDamage = 22; recordSession(game); recordSession(game);
  const report = sessionSummary(game);
  check('session report records ownership changes, unlock time and carrier loss once', report.captured === 1 && report.lost === 1 && report.carrierLosses === 1 && report.unlocks[0]?.time === 123 && report.raids.damage === 22);
  reset();
  check('restarting clears campaign report outcomes', sessionSummary(game).captured === 0 && sessionSummary(game).lost === 0 && sessionSummary(game).unlocks.length === 0 && sessionSummary(game).raids.damage === 0);
  const { theaterChecks } = await import('./theater-checks.js');
  checks.push(...await theaterChecks(api));
  return checks;
}
